/* auto-generated by NAPI-RS */
/* eslint-disable */
/** Compile a JSON string and write the TSON binary to a file. */
export declare function dump(jsonText: string, path: string): void

/** Compile a JSON string to a TSON binary `Buffer`. */
export declare function dumps(jsonText: string): Buffer

/** Emit a JavaScript value directly as TSON binary, bypassing JSON text. */
export declare function emit(val: any): Buffer

/** Read a TSON file and decompile to a JavaScript value. */
export declare function load(path: string): any

/** Decompile a TSON binary `Buffer` to a JavaScript value. */
export declare function loads(bytes: Buffer): any
